"""Shared soundtrack synthesis for Utter promos.

Mix philosophy (v2): one sustained pad, a soft kick + sub-bass pulse only while
the demo is running, one bell per section, and a handful of UI sounds tied to
visible actions. Nothing else, so the bed never competes with the picture.
Utter's start/stop tones reproduce Sources/Audio/SoundPlayer.swift exactly.
"""
import json
import subprocess
import wave
from pathlib import Path

import numpy as np
from scipy.signal import butter, sosfilt

SR = 48000
rng = np.random.default_rng(7)


def load_cues(promo_dir):
    return json.loads((Path(promo_dir) / "scene" / "cues.json").read_text())


def t_axis(seconds):
    return np.arange(int(SR * seconds)) / SR


def midi(n):
    return 440.0 * 2 ** ((n - 69) / 12)


def lowpass(x, cutoff, order=2):
    return sosfilt(butter(order, cutoff, "low", fs=SR, output="sos"), x)


def bandpass(x, lo, hi, order=2):
    return sosfilt(butter(order, [lo, hi], "band", fs=SR, output="sos"), x)


class Mix:
    def __init__(self, duration):
        self.duration = duration
        self.bed = np.zeros((int(SR * duration), 2))
        self.fx = np.zeros((int(SR * duration), 2))
        self.voice = np.zeros((int(SR * duration), 2))
        self.voice_spans = []

    def place(self, start, sig, gain=1.0, pan=0.0, bus="fx"):
        buf = {"fx": self.fx, "bed": self.bed, "voice": self.voice}[bus]
        i = int(start * SR)
        j = min(len(buf), i + len(sig))
        if j <= i or i < 0:
            return
        left, right = np.cos((pan + 1) * np.pi / 4), np.sin((pan + 1) * np.pi / 4)
        buf[i:j, 0] += sig[: j - i] * gain * left * np.sqrt(2)
        buf[i:j, 1] += sig[: j - i] * gain * right * np.sqrt(2)

    def voice_envelope(self, attack=0.12, release=0.3):
        """1 while a voice-over line is speaking (from the manifest spans), with soft ramps."""
        t = t_axis(self.duration)[: len(self.bed)]
        env = np.zeros(len(t))
        for a, b in self.voice_spans:
            env = np.maximum(env, np.clip((t - (a - attack)) / attack, 0, 1) * np.clip(((b + release) - t) / release, 0, 1))
        return env

    def write(self, path, duck=0.45, voice_duck=0.7):
        # Duck the bed under sound effects, and much harder while someone is speaking.
        fx_env = np.clip(lowpass(np.minimum(1, np.abs(self.fx).max(axis=1) / 0.08), 6), 0, 1)
        v_env = self.voice_envelope()
        gain = 1 - np.maximum(duck * fx_env, voice_duck * v_env)
        if self.voice_spans:
            gain *= 0.7  # voiced cuts: keep the bed about 3 dB lower overall
        out = self.bed * gain[:, None] + self.fx * (1 - 0.55 * v_env)[:, None] + self.voice
        t = t_axis(self.duration)[: len(out)]
        out *= (np.clip((self.duration - t) / 1.2, 0, 1) * np.clip(t / 0.25, 0, 1))[:, None]
        out /= max(1e-9, np.abs(out).max()) / 0.89
        with wave.open(str(path), "wb") as w:
            w.setnchannels(2)
            w.setsampwidth(2)
            w.setframerate(SR)
            w.writeframes((out * 32767).astype("<i2").tobytes())


# ---------- Voice-over (generated by voice.py) ----------
def load_audio(path):
    pcm = subprocess.run(["ffmpeg", "-loglevel", "error", "-i", str(path), "-ac", "1", "-ar", str(SR), "-f", "f32le", "-"],
                         check=True, capture_output=True).stdout
    return np.frombuffer(pcm, dtype="<f4").astype(float)


def place_voice(mix, promo_dir, level=0.11):
    """Mixes voice/manifest.json clips, each RMS-matched so narrator and speaker sit at one level."""
    manifest = Path(promo_dir) / "voice" / "manifest.json"
    if not manifest.exists():
        return
    for m in json.loads(manifest.read_text()):
        sig = load_audio(manifest.parent / m["file"])
        frames = sig[: len(sig) // 960 * 960].reshape(-1, 960)
        frame_rms = np.sqrt((frames ** 2).mean(axis=1))
        active = frame_rms[frame_rms > frame_rms.max() * 0.1]
        rms = np.sqrt(np.mean(active ** 2)) if len(active) else 1.0
        mix.place(m["start"], sig * (level / rms) * m.get("gain", 1.0), 1.0, 0.0, bus="voice")
        mix.voice_spans.append(tuple(m["speech"]))


# ---------- Utter's own tones (SoundPlayer.playTone) ----------
def utter_tone(freqs, duration, volume):
    t = t_axis(duration)
    note_len = duration / len(freqs)
    idx = np.minimum((t / note_len).astype(int), len(freqs) - 1)
    f = np.array(freqs, dtype=float)[idx]
    env = 0.5 * (1 - np.cos(2 * np.pi * (t - idx * note_len) / note_len))
    return (np.sin(2 * np.pi * f * t) + 0.25 * np.sin(2 * np.pi * f * 2 * t)) * env * volume


def start_tone():
    return utter_tone([523, 659], 0.16, 0.22)


def stop_tone():
    return utter_tone([494, 392], 0.14, 0.18)


# ---------- UI sound design ----------
def noise(seconds):
    return rng.standard_normal(int(SR * seconds))


def click(level=1.0):
    t = t_axis(0.03)
    n = bandpass(noise(0.03), 1800, 7000) * np.exp(-t / 0.004)
    return (0.5 * n / (np.abs(n).max() + 1e-9) + 0.4 * np.sin(2 * np.pi * 2400 * t) * np.exp(-t / 0.006)) * level


def key_thock(level=1.0, pitch=170):
    t = t_axis(0.14)
    body = np.sin(2 * np.pi * pitch * t * (1 - 0.25 * t)) * np.exp(-t / 0.035)
    snap = bandpass(noise(0.14), 500, 3500) * np.exp(-t / 0.008)
    return (0.8 * body + 0.5 * snap / (np.abs(snap).max() + 1e-9)) * level


def whoosh(seconds, lo=300, hi=4000, level=1.0):
    t = t_axis(seconds)
    n = bandpass(noise(seconds), lo, hi)
    return n / (np.abs(n).max() + 1e-9) * np.sin(np.pi * t / seconds) ** 2 * level


def bell(freq, seconds=1.6, level=1.0):
    t = t_axis(seconds)
    sig = sum(a * np.sin(2 * np.pi * freq * m * t) * np.exp(-t / (seconds * d * 0.35))
              for m, a, d in [(1, 1.0, 1.0), (2.0, 0.3, 0.6), (3.01, 0.08, 0.35)])
    return sig * np.minimum(1, t / 0.004) * level


def soft_pop(level=1.0):
    t = t_axis(0.09)
    return np.sin(2 * np.pi * (660 - 2000 * t) * t) * np.exp(-t / 0.02) * level


# ---------- Music ----------
def pad(mix, chords, end, gain=0.11, xfade=0.5):
    """chords: [(start, [midi...]), ...]; each chord crossfades into the next."""
    for k, (start, notes) in enumerate(chords):
        stop = chords[k + 1][0] if k + 1 < len(chords) else end
        seconds = stop - start + xfade
        t = t_axis(seconds)
        env = np.minimum(1, t / xfade) * np.clip((seconds - t) / xfade, 0, 1)
        sig = sum(np.sin(2 * np.pi * midi(n) * (1 + 0.002 * (i - 1.5)) * t + i) for i, n in enumerate(notes))
        sig += 0.25 * sum(np.sin(2 * np.pi * midi(n) * 2.0 * t) for n in notes[:2])
        sig = lowpass(sig / len(notes), 900)
        mix.place(start - (xfade if k else 0) / 2, sig * env, gain, bus="bed")


def kick(level=1.0):
    t = t_axis(0.32)
    f = 48 + 70 * np.exp(-t / 0.03)
    return np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-t / 0.11) * level


def pulse(mix, ranges, bpm, chords, gain=0.32):
    """Soft kick on every beat + sub-bass root on beats 1 and 3, inside [a, b) ranges."""
    beat = 60 / bpm
    for a, b in ranges:
        n, t = 0, a
        while t < b - 0.05:
            fade = min(1, (t - a) / (beat * 2) + 0.35) * min(1, (b - t) / beat)
            mix.place(t, kick(), gain * 0.8 * fade, bus="bed")
            if n % 2 == 0:
                root = [c for c in chords if c[0] <= t + 1e-6][-1][1][0] - 12
                tt = t_axis(beat * 1.9)
                sub = np.sin(2 * np.pi * midi(root) * tt) * np.minimum(1, tt / 0.02) * np.exp(-tt / (beat * 1.4))
                mix.place(t, sub, gain * 0.55 * fade, bus="bed")
            t += beat
            n += 1


def section_bells(mix, times, notes, gain=0.05):
    for i, t in enumerate(times):
        mix.place(t, bell(midi(notes[i % len(notes)]), 2.2), gain, pan=0.25 if i % 2 else -0.25, bus="bed")


def end_bloom(mix, t0, notes=(74, 78, 81, 86)):
    mix.place(t0, whoosh(0.9, 300, 5000), 0.06)
    for i, n in enumerate(notes):
        mix.place(t0 + 0.05 + i * 0.07, bell(midi(n), 2.8), 0.045, pan=-0.3 + i * 0.2)


def dictation(mix, keydown, keyup, phases, done, land=None, shift=False):
    """Sounds for one hold-to-talk beat; phases are the status-change times."""
    mix.place(keydown, key_thock(), 0.42, -0.5)
    if shift:
        mix.place(keydown - 0.06, key_thock(0.8, 200), 0.3, -0.6)
    mix.place(keydown + 0.05, start_tone(), 1.5)
    mix.place(keyup, key_thock(0.6, 210), 0.32, -0.5)
    mix.place(keyup + 0.03, stop_tone(), 1.5)
    for p in phases:
        mix.place(p, click(0.45), 0.16)
    if land is not None:
        mix.place(land, soft_pop(), 0.22)
    mix.place(done, bell(midi(88), 1.2), 0.06, -0.15)
    mix.place(done + 0.08, bell(midi(95), 1.4), 0.05, 0.15)
