import Foundation
import UtterContracts

extension SettingsStore {
    func persist(_ values: SettingsValues) {
        defaults.set(values.hotkeyAccessibilityPrompted, forKey: Key.hotkeyAccessibilityPrompted.rawValue)
        defaults.set(values.hotkeyType.rawValue, forKey: Key.hotkeyType.rawValue)
        defaults.set(values.translationHotkeyModifier.rawValue, forKey: Key.translationHotkeyModifier.rawValue)
        defaults.set(values.activationMode.rawValue, forKey: Key.activationMode.rawValue)
        defaults.set(values.tapInterval, forKey: Key.tapInterval.rawValue)
        defaults.set(values.speechEngine.rawValue, forKey: Key.speechEngine.rawValue)
        defaults.set(values.whisperModel, forKey: Key.whisperModel.rawValue)
        defaults.set(values.llmModel, forKey: Key.llmModel.rawValue)
        defaults.set(values.microphoneID, forKey: Key.microphoneID.rawValue)
        defaults.set(values.remoteMicEnabled, forKey: Key.remoteMicEnabled.rawValue)
        defaults.set(values.remoteMicGainDB, forKey: Key.remoteMicGainDB.rawValue)
        defaults.set(values.audioGateSensitivity.rawValue, forKey: Key.audioGateSensitivity.rawValue)
        defaults.set(values.audioWeakSpeechSensitivity.rawValue, forKey: Key.audioWeakSpeechSensitivity.rawValue)
        defaults.set(values.outputMode.rawValue, forKey: Key.outputMode.rawValue)
        defaults.set(values.languageStyle.rawValue, forKey: Key.languageStyle.rawValue)
        defaults.set(values.customStylePrompt, forKey: Key.customStylePrompt.rawValue)
        defaults.set(values.playSounds, forKey: Key.playSounds.rawValue)
        defaults.set(values.enableStreamingRecognitionBeta, forKey: Key.enableStreamingRecognitionBeta.rawValue)
        defaults.set(values.inputLanguage.rawValue, forKey: Key.inputLanguage.rawValue)
        defaults.set(values.translationTargetLanguage.rawValue, forKey: Key.translationTargetLanguage.rawValue)
        defaults.set(values.useScreenContext, forKey: Key.useScreenContext.rawValue)
        defaults.set(values.screenContextMode.rawValue, forKey: Key.screenContextMode.rawValue)
        defaults.set(values.enableInstantInsert, forKey: Key.enableInstantInsert.rawValue)
        defaults.set(values.hasCompletedOnboarding, forKey: Key.hasCompletedOnboarding.rawValue)
        defaults.set(values.uiLanguage.rawValue, forKey: Key.uiLanguage.rawValue)
        defaults.set(values.historyRetention.rawValue, forKey: Key.historyRetention.rawValue)
        defaults.set(values.enableMemory, forKey: Key.enableMemory.rawValue)
        defaults.set(values.memoryWindowMinutes, forKey: Key.memoryWindowMinutes.rawValue)
        defaults.set(values.enableCorrectionLearning, forKey: Key.enableCorrectionLearning.rawValue)
        defaults.set(values.industryLexicon.rawValue, forKey: Key.industryLexicon.rawValue)
        defaults.set(values.useCustomSystemPrompt, forKey: Key.useCustomSystemPrompt.rawValue)
        defaults.set(values.customSystemPrompt, forKey: Key.customSystemPrompt.rawValue)
        defaults.set(values.useRemoteLLM, forKey: Key.useRemoteLLM.rawValue)
        defaults.set(values.localLLMBackend.rawValue, forKey: Key.localLLMBackend.rawValue)
        defaults.set(values.espressoModelPath, forKey: Key.espressoModelPath.rawValue)
        defaults.set(values.fallbackToMLXOnEspressoFailure, forKey: Key.fallbackToMLXOnEspressoFailure.rawValue)
        defaults.set(values.remoteProvider.rawValue, forKey: Key.remoteProvider.rawValue)
        defaults.set(values.remoteAPIKey, forKey: Key.remoteAPIKey.rawValue)
        defaults.set(values.remoteBaseURL, forKey: Key.remoteBaseURL.rawValue)
        defaults.set(values.remoteModel, forKey: Key.remoteModel.rawValue)
        defaults.set(values.menuBarIcon.rawValue, forKey: Key.menuBarIcon.rawValue)
        defaults.set(values.appIconAppearance.rawValue, forKey: Key.appIconAppearance.rawValue)
        defaults.set(values.volcAppKey, forKey: Key.volcAppKey.rawValue)
        defaults.set(values.volcAccessKey, forKey: Key.volcAccessKey.rawValue)
        defaults.set(values.volcResourceId, forKey: Key.volcResourceId.rawValue)
        defaults.set(values.qwenASRModel, forKey: Key.qwenASRModel.rawValue)
        defaults.set(values.preloadSpeechModelOnLaunch, forKey: Key.preloadSpeechModelOnLaunch.rawValue)
        defaults.set(values.preloadFormattingModelOnLaunch, forKey: Key.preloadFormattingModelOnLaunch.rawValue)
        defaults.set(values.modelStoragePath, forKey: Key.modelStoragePath.rawValue)
        defaults.set(values.localWhisperModelPaths, forKey: Key.localWhisperModelPaths.rawValue)
        defaults.set(values.localLLMModelPaths, forKey: Key.localLLMModelPaths.rawValue)
        defaults.set(values.developerInterfaceEnabled, forKey: Key.developerInterfaceEnabled.rawValue)
        defaults.set(values.developerHTTPPort, forKey: Key.developerHTTPPort.rawValue)
        defaults.set(values.developerHTTPToken, forKey: Key.developerHTTPToken.rawValue)
    }
}
